Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MKsEMS.Data;
using MKsEMS.Models;

namespace MKsEMS.Controllers
{
    public class JobsController : Controller
    {
        private readonly EMSDbContext _context;
        private readonly CurrentUser2 _loggedInUser;


        public JobsController(EMSDbContext context, CurrentUser2 currentUser)
        {
            _context = context;
            _loggedInUser = currentUser;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            if (!_loggedInUser.IsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "UserLogins");
            }

            return _context.Jobs != null ? 
                          View(await _context.Jobs.ToListAsync()) :
                          Problem("Entity set 'EMSDbContext.Jobs'  is null.");
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!_loggedInUser.IsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "UserLogins");
            }

            if (id == null || _context.Jobs == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobTitle,Salary,Description,IsActive")] Job job)
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            if (id == null || _context.Jobs == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JobTitle,Salary,Description,IsActive")] Job job)
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            if (id == null || _context.Jobs == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!AdminUserIsLoggedIn())
            {
                TempData["AdminMessage"] = "Please login as an Administrator";
                return RedirectToAction("Index", "Users");
            }

            if (_context.Jobs == null)
            {
                return Problem("Entity set 'EMSDbContext.Jobs'  is null.");
            }
            var job = await _context.Jobs.FindAsync(id);
            if (job != null)
            {
                job.IsActive = false;
               //  _context.Jobs.Remove(job);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminUserIsLoggedIn()
        {
            if (_loggedInUser.GetLoggedInUser() == null)
                return false;


            if (_loggedInUser.IsLoggedIn() && _loggedInUser.GetLoggedInUser().IsAdmin)
                return true;

            return false;
        }
        private bool JobExists(int id)
        {
          return (_context.Jobs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor contex
@inject CurrentUser2 user
@*@inject EMSDbContext _context*@

@using MKsEMS.Data

@using MKsEMS.Controllers
@using Microsoft.AspNetCore.Http;
@{
    var email = "";
    var name = "";
    var currentYear = DateTime.Now.Year;
    var compName = "No company set up yet!";

    bool loggedin = false;
    if (user.GetLoggedInUser() != null)
    {
        name = string.Concat(user.GetLoggedInUser().FirstName, " ", user.GetLoggedInUser().Surname);
        email = user.GetLoggedInUser().Email;
        loggedin = true;
    }

    ViewData["Title"] = "Index";
    var welcomeMsg = "Welcome ";
    var _context = new EMSDbContext();
    var comp = _context.Companies.ToList().Where(c => !c.IsToBeDeleted).FirstOrDefault();

    if (comp != null)
    {
        compName = comp.Name;
        welcomeMsg = String.Concat(welcomeMsg, "to ", comp.Name);
    }
    

    
    if (TempData["CompanyMsg"] != null)  {
       
        welcomeMsg = TempData["CompanyMsg"].ToString();
        //welcomeMsg += "- Please ensure there is an active Conpany Details set up!";
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["JobTitle"] EMS Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MKsEMS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 position-fixed vw-100">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MKsEMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <img src="~/images/mksems.png" class="img-fluid" height="50" width="50" alt="Responsive image">
                        </li>

                        @{
                            if(loggedin){

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Leaves" asp-action="Index">Leaves</a>
                                </li> 
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                                </li>
                                if(  user.GetLoggedInUser().IsAdmin
                                  || user.GetLoggedInUser().IsManager
                                  || user.GetLoggedInUser().IsCEO
                                 )
                                {
                                    
                                    
                                    if (user.GetLoggedInUser().IsAdmin || user.GetLoggedInUser().IsCEO)
                                    {
                                        <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="LeaveAllowances" asp-action="Index">Leave Allowances</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Company detail</a>
                                        </li>
                                    }
                                }

                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResetPasses" asp-action="ResetPassword">Password Reset</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserLogins" asp-action="Index">Login</a>
                        </li>                      
                    </ul>
                </div>
                <div class="align-content-lg-end m-3">@name</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3"> 
            @{
                if (TempData["CompanyMsg"] != null)
                {
                    <br /><br /><br /><br />
                    <div class="text-danger">
                        <h1>
                            
                            @welcomeMsg
                        </h1>

                    </div>
                }
                else
                {
                     <h1>
                        @welcomeMsg
                    </h1>
                }                               
           }           
            <br />
             
            <p>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @currentYear - @compName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>